config/routes.rb
Propest::Application.routes.draw do
  resources :publicacions do
    get 'search', on: :collection
    post 'search', on: :collection
    post 'cambiar_estado', on: :collection
  end

  devise_for :users

   root 'welcome#index'

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/publicacion.rb
class Publicacion < ActiveRecord::Base
	belongs_to :user
	validates :pieza, :bano, :precio,numericality: { only_integer: true, greater_than: 0 }, presence: true
	validates :titulo, :descripcion, :region, :ciudad, :direccion, presence: true
	has_many :attachments, :as => :attachable
	accepts_nested_attributes_for :attachments,:allow_destroy => true
  before_update :check_map

	def twitter
		config = {
          :consumer_key        => "0k9QQODmhmVcPUusziFakkBpI",
          :consumer_secret     => "p1W1tSgwwBt0K1aMpSgsz863hw0xZJCihoxDWFhpYF4cqnie13",
          :access_token        => "2490114194-yVvLnTxJBkSfdXNVnQ6YjDHgCekJ6ikSnU3LdQx",
          :access_token_secret => "ISijaSf6OBOssSNL3j0AZivePLyGkFKCDj2fDl0L1z3j0",
        }
        client = Twitter::REST::Client.new(config)
    end

    def smallImage
      if self.attachments.last != nil
        imagen = self.attachments.last.file_url(:small)
      else
        return nil
      end
    end

    def largeImage
      if self.attachments.last != nil
        imagen = self.attachments.last.file_url(:large)
      else
        return nil
      end
    end

    def ultimasPropiedades
    result = Publicacion.find(:all, :order => "id desc", :limit => 5)
    return result
    end

    def check_map
    if self.latitude == 1
      self.latitude = latitude_was
      self.longitude = longitude_was
    end
    end

end

app/controllers/publicacions_controller.rb
class PublicacionsController < ApplicationController
  before_action :set_publicacion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :search]
  before_action :check_publicacion, only: [:edit, :update, :destroy] 

  # GET /publicacions
  # GET /publicacions.json
  def index
    @user = current_user
    @publicacion =  @user.publicacions.order! 'created_at DESC'
  end

  # GET /publicacions/1
  # GET /publicacions/1.json
  def show
    @user = User.find_by_id(@publicacion.user_id)
  end

  # GET /publicacions/new
  def new
    @publicacion = Publicacion.new
  end

  # GET /publicacions/1/edit
  def edit
  end

  # POST /publicacions
  # POST /publicacions.json
  def create
    @user = current_user
    @publicacion = @user.publicacions.new(publicacion_params)
    respond_to do |format|
      if @publicacion.save
        bitly = Bitly.client
        bitId = 2
        link = bitly.shorten("http://propes.herokuapp.com/publicacions/#{bitId}").short_url
        client=@publicacion.twitter
        client.update("#{@publicacion.titulo}, #{@publicacion.ciudad}, Precio: #{@publicacion.precio}. Conocela: #{link}")
        format.html { redirect_to @publicacion }
        format.json { render action: 'show', status: :created, location: @publicacion }
      else
        format.html { render action: 'new' }
        format.json { render json: @publicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publicacions/1
  # PATCH/PUT /publicacions/1.json
  def update
    respond_to do |format|
      if @publicacion.update(publicacion_params)
        format.html { redirect_to @publicacion, notice: 'Publicacion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @publicacion.errors, status: :unprocessable_entity }
      end
    end
  end


  def search
    if user_signed_in?
      @user = current_user
    end
    if params[:searchParams] #Llegan parametros por el welcome
      @search = Publicacion.search(params[:searchParams])
      @publicacion=@search.result.page(params[:page]).per(2)
    else
      @search = Publicacion.search(params[:q])
      @publicacion=@search.result.page(params[:page]).per(2)
    end
  end
  # DELETE /publicacions/1
  # DELETE /publicacions/1.json
  def destroy
    @publicacion.destroy
    respond_to do |format|
      format.html { redirect_to publicacions_url }
      format.json { head :no_content }
    end
  end

   def cambiar_estado
      @publicacion = Publicacion.find_by_id(params[:publicacion][:id])
      estado = !@publicacion.estado
      @publicacion.update_attributes({:estado => estado})
        respond_to do |format|
          format.html { redirect_to publicacions_url }
          format.js
        end
     end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publicacion
      @publicacion = Publicacion.find_by_id(params[:id])
    end

    def check_publicacion
      @user=current_user
      id=params[:id]
      if (@user.publicacions.find_by_id(id) == nil)
         flash[:error] = "Accion no permitida"
         redirect_to url_for(:controller => :welcome, :action => :index)
       end
     end


    # Never trust parameters from the scary internet, only allow the white list through.
    def publicacion_params
      params.require(:publicacion).permit(:pieza, :direccion, :precio, :bano, :estacionamiento, :tipo, :ciudad, :region, :comparte, :md, :latitude, :longitude,:titulo, :descripcion, :aire, :balcon, :calefaccion, :piscina, :multiuso, :spa, :computacion, :conserje, :lavado, :cine, :visita, :quincho, :juegos, :cocina, :infantiles, :superficie, :contrato, :estado,attachments_attributes: [:id, :file, :file_cache, :_destroy])
    end
end

app/helpers/publicacions_helper.rb
module PublicacionsHelper
end

app/views/publicacions/_publicacion.html.erb
   <div class="property span9">
            <div class="row">
                <div class="image span3">
                    <div class="content">
                        <%=link_to "",publicacion%>
                        <% if publicacion.attachments != nil %>
                                <%= image_tag publicacion.smallImage %> 
                                <% end %>
                    </div><!-- /.content -->
                </div><!-- /.image -->

                <div class="body span6">
                    <div class="title-price row">
                        <div class="title span4">
                            <h2><%= link_to publicacion.titulo, publicacion %></h2>
                        </div><!-- /.title -->

                        <div class="price">
                            $<%= publicacion.precio %>
                        </div><!-- /.price -->
                    </div><!-- /.title -->

                    <div class="location"><%= publicacion.ciudad %></div><!-- /.location -->
                    <p> <%= truncate(publicacion.descripcion, :length => 135 )%></p>
                    <div class="area">
                        <span class="key">Superficie:</span><!-- /.key -->
                        <span class="value"><%= publicacion.superficie %>m<sup>2</sup></span><!-- /.value -->
                    </div><!-- /.area -->
                    <div class="bedrooms"><div class="content"><%= publicacion.pieza %></div></div><!-- /.bedrooms -->
                    <div class="bathrooms"><div class="content"><%= publicacion.bano %></div></div><!-- /.bathrooms -->
                </div><!-- /.body -->
            </div><!-- /.property -->
        </div><!-- /.row -->

app/views/publicacions/edit.html.erb
<div id="content">
<div class="container">
    <div>
        <div id="main">
            <div class="list-your-property-form">
    <h2 class="page-header">Editar Propiedad</h2>

    <div class="content">
        <div class="row">
            <div class="span8">
                <p>
                    Modifique todos los campos que usted desea actualizar de la propiedad. 
                </p>
            </div><!-- /.span8 -->
        </div><!-- /.row -->

<%= render 'form' %>

</div><!-- /.content -->
</div><!-- /.list-your-property-form -->        </div>
    </div>
</div>

    </div><!-- /#content -->
</div><!-- /#wrapper-inner -->

app/views/publicacions/index.html.erb
<div id="content">
<div class="container">

    <div id="main">
        <div class="row">
            <div class="span9">
                <h1 class="page-header">Propiedades</h1>

                <div class="properties-rows">
    <div class="row">
        <% @publicacion.each do |publicacion| %>    
        <div class="property span9">
            <div class="row">
                <div class="image span3">
                    <div class="content">
                    <%=link_to "",publicacion%>
                    <% if publicacion.smallImage != nil %>
                    <%= image_tag publicacion.smallImage %>
                    <% else %>
                    <%= image_tag "no-image.gif" %>
                    <% end %> 
                    </div><!-- /.content -->
                </div><!-- /.image -->

                <div class="body span6">
                    <div class="title-price row">
                        <div class="title span4">
                            <h2><%= link_to publicacion.direccion, publicacion %></h2>
                        </div><!-- /.title -->

                        <div class="price">
                            $<%= publicacion.precio %>
                        </div><!-- /.price -->
                    </div><!-- /.title -->

                    <div class="location"><%= publicacion.ciudad %></div><!-- /.location -->
                    <p>
                        <%= truncate publicacion.descripcion, length: 135 %>
                    </p>
                    <div class="area">
                        <span class="key">Superficie(mts<sup>2</sup>):</span><!-- /.key -->
                        <span class="value"><%= publicacion.superficie %></span><!-- /.value -->
                    </div><!-- /.area -->
                    <div class="bedrooms">
                    <div class="content"><%= publicacion.pieza %></div>
                    </div><!-- /.bedrooms -->
                    <div class="bathrooms">
                    <div class="content"><%= publicacion.bano %></div>
                    </div><!-- /.bathrooms -->
                    <%= simple_form_for publicacion, :url => url_for(:action => 'cambiar_estado', :controller => 'publicacions'),
                     :method => 'post'  do |f| %>
                     <div><%= f.hidden_field :id %></div>
                     <% if publicacion.estado %>
                      <%= f.submit "Pausar", class: "btn btn-primary" %>
                      <% else %>
                      <%= f.submit "Activar", class: "btn btn-primary" %>
                     <% end %>
                     <% end %>
                     <%=link_to "Editar",edit_publicacion_path(publicacion), { :class=>"btn btn-primary" }%>
                    <%= link_to "Eliminar", publicacion_path(publicacion), :confirm => "¿Eliminar Propiedad?", :method => :delete,:class=>"btn btn-danger" %>
                </div><!-- /.body -->
            </div><!-- /.property -->
        </div><!-- /.row -->
         <% end %>
    </div><!-- /.row -->
</div><!-- /.properties-rows -->
                <div class="pagination pagination-centered">
    <ul>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li class="active"><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">next</a></li>
        <li><a href="#">last</a></li>
    </ul>
</div><!-- /.pagination -->            </div>
        </div>
    </div>
</div>

    </div><!-- /#content -->
</div><!-- /#wrapper-inner -->

<%
=begin
%>
<div id="main_content">
    
    
    <div id="admin_header">
      <div class="admin_index_title">Mis Publicaciones</div>        
        </div>
<div class="table_grid">
                <table cellspacing="0" cellpadding="0">
                    <tr>
                        <b><th style="width:auto;"class="pink"><p class="pink">Titulo</p></th>
                        <th style="width:auto;"class="pink"><p class="pink">Valor</p></th>
                        <th style="width:auto;"class="pink"><p class="pink">Editar</p></th>
                        <th style="width:auto;"class="pink"><p class="pink">Eliminar</p></th>
                        </b>
                    </tr>
  <tbody>
    <% @publicacion.each do |publicacion| %>
      <tr class="even">
        <td><%= link_to publicacion.titulo, publicacion %></td>
        <td><%= publicacion.precio %></td>
        <td><%=link_to( image_tag("images/adminicons/edit.png", :alt => "Edit", :title => "Edit", :size => "22x22"), edit_publicacion_path(publicacion)) %></td>
         <td><%= link_to (image_tag "images/adminicons/delete.png", :alt => "Eliminar", :title => "Eliminar", :size => "24x24"), publicacion, method: :delete, data: { confirm: '¿Estás Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="right_buttons">
    <div class="right_button">
      <%= link_to 'Publicar Propiedad', new_publicacion_path %>
    </div>
    <div class="right_button">
      <%= link_to 'Volver', :back %>
    </div>
</div>


</div>
<%
=end
%>

app/views/publicacions/new.html.erb
 <div id="content">
<div class="container">
    <div>
        <div id="main">
            <div class="list-your-property-form">
    <h2 class="page-header">Publicar Propiedad</h2>

    <div class="content">
        <div class="row">
            <div class="span8">
                <p>
                    Ingrese toda la información necesaria en los campos siguientes, información que debe describir la propiedad lo más exacta y completa ṕosible, para que los futuros residentes puedan escoger con la mayor cantidad de información. 
                </p>
            </div><!-- /.span8 -->
        </div><!-- /.row -->

        <%= render 'form' %>
</div><!-- /.content -->
</div><!-- /.list-your-property-form -->        </div>
    </div>
</div>

    </div><!-- /#content -->
</div><!-- /#wrapper-inner -->

app/views/publicacions/search.html.erb
<!-- CONTENT -->
            <div id="content">
<div class="container">

    <div id="main">
        <div class="row">
            <div class="span9">
                <h1 class="page-header">Propiedades Disponibles</h1>

                <div class="properties-rows">
<div class="filter">
    <form action="http://html.realia.byaviators.com/listing-rows-filter.html?" method="get" class="form-horizontal">
     <div class="btn-group">
        <div class="control-group">
            <label class="control-label" for="inputSortBy">
                Ordenar por
                <span class="form-required" title="This field is required.">*</span>
            </label>
            <div class="controls">
                <div class="btn btn-default">
                <%= sort_link(@search, :precio, "Precio") %>
                </div>
                <div class="btn btn-default">
                <%= sort_link(@search, :created_at, "Fecha",  html_options: { :class=>"btn btn-primary btn-large list-your-property arrow-right" }) %>
                </div>
            </div><!-- /.controls -->
        </div><!-- /.control-group -->
        </div>
    </form>
</div><!-- /.filter -->
</div><!-- /.properties-rows -->                
<div class="properties-rows">
    <div class="row">
      <% if @publicacion.size >0 %>
      <div id="propiedad_publicada">
        <%= render @publicacion %>
      </div>
      <% else %>
        <h2>No existen coincidencias</h2>
      <% end %>
    </div><!-- /.row -->
</div><!-- /.properties-rows -->
  <div class="pagination pagination-centered" id="paginator">
   <%= paginate @publicacion, :remote => true %> 
  </div>           
</div>
            

                <div class="sidebar span3">
                <h2>Filtrar Búsqueda</h2>
<div class="property-filter">
                        <div class="content">
                        <%= simple_form_for @search, :url => search_publicacions_path,
    :method => 'get' do |f| %>
                                <div class="location control-group">
                                    <label class="control-label" for="inputLocation">
                                        Comuna
                                    </label>
                                    <div class="controls">
                                        <%= f.input :ciudad_eq, collection: [ "Puerto Montt", "Viña Del Mar", "Valparaiso"], label: false %>
                                    </div><!-- /.controls -->
                                </div><!-- /.control-group -->

                                <div class="type control-group">
                                    <label class="control-label" for="inputType">
                                        Tipo
                                    </label>
                                    <div class="controls">
                                        <%= f.input :tipo_eq, collection: [ "Departamento", "Casa", "Pension", "Departamento Compartido"], label: false %>
                                    </div><!-- /.controls -->
                                </div><!-- /.control-group -->

                                <div class="beds control-group">
                                    <label class="control-label" for="inputBeds">
                                        Dormitorios
                                    </label>
                                    <div class="controls">
                                        <%= f.input :pieza_eq, collection: 1..4, label: false %>
                                    </div><!-- /.controls -->
                                </div><!-- /.control-group -->

                                <div class="baths control-group">
                                    <label class="control-label" for="inputBaths">
                                        Baños
                                    </label>
                                    <div class="controls">
                                        <%= f.input :bano_eq, collection: 1..3, label: false %>
                                    </div><!-- /.controls -->
                                </div><!-- /.control-group -->

                                <div class="price-from control-group">
                                    <label class="control-label" for="inputPriceFrom">
                                        Price from
                                    </label>
                                    <div class="controls">
                                          <%= f.input :precio_gteq, input_html: { id: 'inputPriceFrom', name: 'inputPriceFrom' } %>
                                    </div><!-- /.controls -->
                                </div><!-- /.control-group -->

                                <div class="price-to control-group">
                                    <label class="control-label" for="inputPriceTo">
                                        Price to
                                    </label>
                                    <div class="controls">
                                        <%= f.input :precio_lteq, input_html: { id: 'inputPriceTo', name: 'inputPriceTo' } %>
                                    </div><!-- /.controls -->
                                </div><!-- /.control-group -->

                                <div class="price-value">
                                    <span class="from"></span><!-- /.from -->
                                    -
                                    <span class="to"></span><!-- /.to -->
                                </div><!-- /.price-value -->

                                <div class="price-slider">
                                </div><!-- /.price-slider -->
                                
                                <div class="form-actions">
                                    <%= f.button :submit, "Buscar Ahora!", class: "btn btn-primary btn-large" %>
                                </div><!-- /.form-actions -->
                            <% end %>
                        </div><!-- /.content -->
                    </div><!-- /.property-filter -->
            </div>
        </div>
    </div>
</div>

    </div><!-- /#content -->
</div><!-- /#wrapper-inner -->
<%
=begin


<div class="column1">
<% if @comuna %>
<h2> La Comuna ES: <%= @comuna %></h2>
<% end %>
<h1>Listado de Propiedades</h1>
<%= search_form_for(@search,url: search_publicacions_path,html: { method: :get }) do |f| %>
    <div class="field">
    <%= f.label :pieza_gteq,"Numero de Piezas entre" %><br>
    <%= f.number_field :pieza_gteq %>
    <%= f.label :pieza_lteq, "y" %>
    <%= f.number_field :pieza_lteq %>    
  </div>
  <div class="field">
    <%= f.label :bano_gteq,"Numero de Baños entre" %><br>
    <%= f.number_field :bano_gteq %>
    <%= f.label :bano_lteq, "y" %>
    <%= f.number_field :bano_lteq %>    
  </div>
    <div class="field">
    <%= f.label :precio_gteq,"Precio entre" %><br>
    <%= f.number_field :precio_gteq %>
    <%= f.label :precio_lteq, "y" %>
    <%= f.number_field :precio_lteq %>    
  </div>
  <%= f.hidden_field :tags_list, :value => '1' %>
  <%= f.submit "Buscar" %>
<% end %>
<% if @publicacion.size >0 %>
<div id="main_content">
<div id="admin_header">
<h1>Propiedades encontradas</h1>
<div class="table_grid">
<table cellspacing="0" cellpadding="0">
  <thead>
  <tr>
       <th style="width:auto;"class="pink"><p class="pink">Titulo</p></th>
      <th style="width:auto;"class="pink"><p class="pink"><%=sort_link(@search, :precio, "Pecio") %></p></th>
      <th style="width:auto;"class="pink"><p class="pink"><%=sort_link(@search, :created_at, "Fecha Publicación")%></p></th>
      </tr>
 </thead>
 <tbody id="publicacions">
 <%= render @publicacion %>
 </tbody>
</table>
   <div id="paginator" class="pagination">
   <%= paginate @publicacion, :remote => true %> 
   </div>
  <% else %>
  <h2>No existen coincidencias</h2>
  <% end %>
  <% if user_signed_in? %>
  <div class="right_buttons">
    <div class="right_button">
        <%= link_to "Mis Propiedades", {:controller=>"publicacions", :action=>"index"} %>
    </div>
    <div class="right_button">
  <%= link_to "Publicar Propiedad", new_publicacion_path %>
  </div>
  <div class="right_button">
  <%= link_to 'Bandeja de Entrada', :conversations %>
  </div>
  <div class="right_button">
  <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
  </div>
<%else%>
<div class="right_button">
  <%= link_to "Iniciar Sesión", new_user_session_path %>
  </div>
  <div class="right_button">
  <%= link_to "Registrarse", new_user_registration_path %>
  </div>
<%end%>
</div>
 </div>
  </div>
  <%
=end
%>

<%
=begin
%>
<div class="column1">
<h1>Listado de Propiedades</h1>
<%= search_form_for(@search,url: search_publicacions_path,html: { method: :get }) do |f| %>
    <div class="field">
    <%= f.label :pieza_gteq,"Numero de Piezas entre" %><br>
    <%= f.number_field :pieza_gteq %>
    <%= f.label :pieza_lteq, "y" %>
    <%= f.number_field :pieza_lteq %>    
  </div>
  <div class="field">
    <%= f.label :bano_gteq,"Numero de Baños entre" %><br>
    <%= f.number_field :bano_gteq %>
    <%= f.label :bano_lteq, "y" %>
    <%= f.number_field :bano_lteq %>    
  </div>
    <div class="field">
    <%= f.label :precio_gteq,"Precio entre" %><br>
    <%= f.number_field :precio_gteq %>
    <%= f.label :precio_lteq, "y" %>
    <%= f.number_field :precio_lteq %>    
  </div>
  <%= f.hidden_field :tags_list, :value => '1' %>
  <%= f.submit "Buscar" %>
<% end %>
<% if @publicacion.size >0 %>
<div id="main_content">
<div id="admin_header">
      <div class="admin_index_title">Propiedades Encontradas</div>        
        </div>
        <table>
<div class="table_grid">
  <table cellspacing="0" cellpadding="0">
                    <tr>
      <th style="width:auto;"class="pink"><p class="pink">Titulo</p></th>
      <th style="width:auto;"class="pink"><p class="pink"><%=sort_link(@search, :precio, "Pecio") %></p></th>
      <th style="width:auto;"class="pink"><p class="pink"><%=sort_link(@search, :created_at, "Fecha Publicación")%></p></th>
      </tr>
      <tbody>
      <%= render @publicacion %>
      </tbody>
</table>
   <div id="paginator">
   <%= paginate @publicacion, :remote => true %> 
   </div>
  <% else %>
  <h2>No existen coincidencias</h2>
  <% end %>
  <% if user_signed_in? %>
  <div class="right_buttons">
    <div class="right_button">
        <%= link_to "Mis Propiedades", {:controller=>"publicacions", :action=>"index"} %>
    </div>
    <div class="right_button">
  <%= link_to "Publicar Propiedad", new_publicacion_path %>
  </div>
  <div class="right_button">
  <%= link_to 'Bandeja de Entrada', :conversations %>
  </div>
  <div class="right_button">
  <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
  </div>
<%else%>
<div class="right_button">
  <%= link_to "Iniciar Sesión", new_user_session_path %>
  </div>
  <div class="right_button">
  <%= link_to "Registrarse", new_user_registration_path %>
  </div>
<%end%>
</div>
</div>
</div>
</div>

  <%
=end
%>

app/views/publicacions/search.js.erb
$('#propiedad_publicada').html('<%=j render(@publicacion) %>');
$('#paginator').html('<%=j(paginate(@publicacion, :remote => true).to_s) %>');